# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13zeRd9AT4lu8WoJ8-9OoRsCVnxOTm2QE
"""

from scipy.stats import bernoulli
import matplotlib.pyplot as plt
import numpy as np

# conducting the experimwnt of tossing two coins for sim_len times
sim_len=100000
# creating the random outcomes x1 for 1st and x2 for 2nd coins
x1= bernoulli.rvs(size = sim_len, p=1/2)
x2= bernoulli.rvs(size = sim_len, p=1/2)

#c represents no of cases of both heads
c=0
""" cond_count says the number of outcomes in which the given condition of atleast
 one head is satisfied"""
cond_count=0
i=0
while (i<sim_len):
  if (x1[i]==1 or x2[i]==1):
    cond_count+=1
  if (x1[i]==1 and x2[i]==1):
    c+=1
  i+=1

#p represents required probability
p=c/cond_count
print ("The probability value obtained by simulation is ",p)
print ("The probability obtained by the calculation is 1/3")

X = [1,2]
Y = [p, 1/3]
LABELS = ["Prob by simulation", "Prob by calculation"]

plt.bar(X, Y,color='b', align='center')
plt.xticks(X, LABELS)
plt.show()